#!/bin/bash
chmod 777 0-positive_or_negative.c
chmod 777 1-last_digit.c
chmod 777 10-print_comb2.c
chmod 777 100-print_comb3.c
chmod 777 101-print_comb4.c
chmod 777 102-print_comb5.c
chmod 777 2-print_alphabet.c
chmod 777 3-print_alphabets.c
chmod 777 4-print_alphabt.c
chmod 777 5-print_numbers.c
chmod 777 6-print_numberz.c
chmod 777 7-print_tebahpla.c
chmod 777 8-print_base16.c
chmod 777 9-print_comb.c
